### ISSUE TITLE
Organize guide sections

### ISSUE THREAD

**Issue by PumkinSpice** [PumkinSpice/MixedVR#1]
Think three sections may be good:

1. **Space Cal setup (in prereqs: link to read troubleshooting section first? Or maybe add extra notes about must-do, like USB 2.0)**
2. **OVRAS/SteamVR Chaperone setup**
3. **Troubleshooting/known bugs**

**Comment by monstermac77** [comment]
"(in prereqs: link to read troubleshooting section first? Or maybe add extra notes about must-do, like USB 2.0)" 

is done.
