### ISSUE TITLE
Notes during setup for possible guide edits

### ISSUE THREAD

**Issue by PumkinSpice** [PumkinSpice/MixedVR#2]
From @monstermac77 

![notes](https://user-images.githubusercontent.com/72831277/100405039-c533c580-3030-11eb-9be0-eb34105d50b7.png)

**Comment by PumkinSpice** [comment]
Step 13: no paste needed - just copy! (it auto-pastes the first time)

**Comment by monstermac77** [comment]
👌

**Comment by monstermac77** [comment]
Just added the disclaimer about USB 3.0 ports, which has been the biggest cause for tracking issues I believe (anecdotally from discussing with people on the Discord) when first trying to set this up.

**Comment by monstermac77** [comment]
Ok, just completed all of the other relevant items in this list. Here's the git diff: https://github.com/PumkinSpice/MixedVR/wiki/ReadMe/_compare/bedfc5f3a9a66886251a3097759cfcaab5a234d5...a232f858f20bb954921e34345c61f9673e32d440
