### ISSUE TITLE
Change name to "mixedWMR"?

### ISSUE THREAD

**Issue by monstermac77** [PumkinSpice/MixedVR#3]
For branding consistency with https://www.reddit.com/r/MixedVR/. 

Github automatically redirects old repo names to new repo names, so existing links around the internet won't break.

**Comment by PumkinSpice** [comment]
Sounds fine to me! Could even change it to MixedVR as I do have plans to add help for other HMD's like Quest eventually

**Comment by monstermac77** [comment]
Yeah, let’s do that. I think my repo can be the general VR stuff for newcomers, those interested in getting a more technical understanding of VR, and those looking for scripts and ways to perfect their setup. 

And your repo will be the home to all MixedVR guides, troubleshooting, and relevant scripts, etc. Basically the counterpart to the subreddit.

**Comment by PumkinSpice** [comment]
Done! :)
