### ISSUE TITLE
Buttons not working on more than 2 controllers

### ISSUE THREAD

**Issue by jhermen-List** [PumkinSpice/MixedVR#4]
Hi, thanks for the great project! 

So far we have 4 HTC VIVE controllers paired to 4 of the vrdongles. they are all showing up in the SteamVR settings, as well as in the OpenVR python code. All 4 controllers sent location and orientation data. 

The problem we have is that we can only get Button/Trigger/Touchpad events from the first 2 controller. This does not depend on the the controller itself, its working for each controller and dongle, but if more than 2 controllers are actice/powered at the same time, only the first two that were powered on are sending Button/trigger/Touchpad events.

I guess this is related to the thing that SteamVR normally only supports 2 (left/right) controllers. Allthough in the SteamVR Settings the first 2 powered on controllers show up as left/right while the others show up by their internal ID.

Is there a way to get more than 2 controllers working with click etc.. in StreamVR/OpenVR?

Thanks a lot 
       Johannes

**Comment by PumkinSpice** [comment]
Hi there, sorry for the delayed response!

Unfortunately no, there is no way to support more than two controllers at once. It's a limitation of openVR. This is also why you reset steamVR once you have your playspaces sync'd up (so you can turn off your non-lighthouse controllers and guarantee the lighthouse controllers' buttons work).

**Comment by jhermen-List** [comment]
OK, thanks for the info. So we will have to use 2PCs with if we need 4 controllers.
